#ifndef _CUST_PS_RIL_
#define _CUST_PS_RIL_

#define FEATURE_PS_KDDI_UIM

#define FEATURE_PS_KDDI_NO_SIM

#define FEATURE_PS_KDDI_ME_SETTING

#define FEATURE_PS_PIN_EVENT

#define FEATURE_PS_UIM_HIDDEN

#define FEATURE_PS_UIM_FTM

#define FEATURE_PS_UIM_STATUS

#define FEATURE_PS_UIM_MPIN_CHECK

#define FEATURE_PS_FILE_IO_MODIFY

#define FEATURE_PS_UIM_RIL_API

#define FEATURE_PS_UIM_AUTO_PIN

#define FEATURE_PS_UIM_MONITOR_NV

#define FEATURE_PS_UIM_PIN_BACKUP

#define FEATURE_PS_UIM_POLLING_ERR

#define FEATURE_PS_UIM_PIN_STATUS

#define FEATURE_PS_UIM_MDN_LENGTH
#endif

